-- Unless explicitly stated otherwise all files in this repository are licensed under the
-- Apache License Version 2.0.
-- This product includes software developed at Datadog (https://www.datadoghq.com/).
-- Copyright 2026-Present Datadog, Inc.

-- truth: equivalent
-- expect frontend: refuse:parameter-misaligned
-- expect fuzz: not-comparable
-- expect qed: no-plan
-- expect sqleq-solver: no-plan
-- expect sqlsolver-jvm: no-plan
-- expect lean: proved-gather-generated
-- binding: gather-generated
-- origin: an identity column that accepts an explicit value, left to DEFAULT on the VALUES side

CREATE TABLE events (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind text);
INSERT INTO events (id, kind) VALUES (DEFAULT, $1), (DEFAULT, $2);
INSERT INTO events (id, kind) SELECT * FROM unnest($1::bigint[], $2::text[]);
