// Unless explicitly stated otherwise all files in this repository are licensed under the
// Apache License Version 2.0.
// This product includes software developed at Datadog (https://www.datadoghq.com/).
// Copyright 2026-Present Datadog, Inc.

//! The sequence columns sqleq-fuzz filled with NULLs (issue #94).
//!
//! Each equivalent pair here was refuted: the generator drew NULLs into `serial` and identity
//! columns. The non-equivalent one checks that what fixed it still refutes what it should.

use sqleq_fuzz::{test_pair, Config};

/// The budget `sqleq-check` passes, so a verdict here is the one a pinned pair records.
const CFG: Config = Config {
    trials: 120,
    nrows: 5,
    seed: 0,
};

fn label(a: &str, b: &str, ddl: &str) -> String {
    test_pair(a, b, ddl, CFG).label()
}

// -- #94. `serial` and identity columns are NOT NULL ------------------------------------------------

#[test]
fn a_sequence_column_is_never_null() {
    for ddl in [
        r#"create table "t" ("id" SERIAL, "a" INTEGER)"#,
        r#"create table "t" ("id" BIGSERIAL, "a" INTEGER)"#,
        r#"create table "t" ("id" smallserial, "a" INTEGER)"#,
        r#"create table "t" ("id" serial8, "a" INTEGER)"#,
        r#"create table "t" ("id" INTEGER GENERATED ALWAYS AS IDENTITY, "a" INTEGER)"#,
        r#"create table "t" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 10), "a" INTEGER)"#,
    ] {
        assert_eq!(
            label(
                r#"SELECT "a" FROM "t" WHERE "id" IS NOT NULL"#,
                r#"SELECT "a" FROM "t""#,
                ddl
            ),
            "NO-COUNTEREXAMPLE",
            "{ddl}"
        );
    }
}

#[test]
fn a_sequence_column_draws_distinct_values() {
    // Each value at most once, so no two rows share an id; the pair is not equivalent in Postgres
    // (an explicit value may repeat one), which is why this is not a key.
    let ddl = r#"create table "t" ("id" SERIAL, "a" INTEGER)"#;
    assert_eq!(
        label(
            r#"SELECT count(*) FROM "t""#,
            r#"SELECT count(DISTINCT "id") FROM "t""#,
            ddl
        ),
        "NO-COUNTEREXAMPLE"
    );
    // ... and the values are still drawn.
    assert_eq!(
        label(
            r#"SELECT "a" FROM "t" WHERE "id" > 0"#,
            r#"SELECT "a" FROM "t""#,
            ddl
        ),
        "NOT-EQUIVALENT"
    );
}
